# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# ------------------------ Configuration ------------------------
add_newline = true # Insert a new line between shell prompts
command_timeout = 20000
continuation_prompt = "â–¶â–¶"
right_format = "ã€ã«ã‚ƒ~(white)"

[line_break]
disabled = true # Two lines.

[cmd_duration]
disabled = true
show_milliseconds = false
style = "bold italic red"

# Username
[username]
disabled = false
format = "[$user ](#0099ff)"
show_always = true
style_root = "bg:#9A348E"
style_user = "bg:#9A348E"

# Hostname
[hostname]
disabled = false
format = "on [$hostname](#ff3399) "
ssh_only = false
trim_at = "."

# Prompt
[character]
success_symbol = "[ã€Œ](white)"
error_symbol = "[ >_< [ã€Œ]()](bold red)"
vimcmd_replace_one_symbol = "[ã€Œ](white)"
vimcmd_replace_symbol = "[ã€Œ](white)"
vimcmd_symbol = "[ã€Œ](white)"
vimcmd_visual_symbol = "[ã€Œ](white)"
#error_symbol = "[ ãƒŽ_< [ã€Œ]()](bold red)"
# Prompt - Vim mode

# Directory
[directory]
disabled = false
format = "in [$path]($style) "
read_only = "ï ½"
truncation_length = 2
truncation_symbol = ".../"

[directory.substitutions]
"~" = "ó°‹œ "
".config" = "î˜• "
"Desktop" = "ï„ˆ "
"Downloads" = "ó°‡š "
"games" = "ï„› "
"music" = "ï€ "
"sync" = "ï‘ª "

# ------------------------ Icons ------------------------

# Git
[git_branch]
symbol = "ï˜ "
#[git_status]
#style = "167"
#conflicted = "ðŸ³"
#ahead = "ðŸŽðŸ’¨"
#behind = "ðŸ˜°"
#diverged = "ðŸ˜µ"
#up_to_date = "âœ“"
#untracked = "ðŸ¤·â€"
#stashed = "ðŸ“¦"
#modified = "ðŸ“"
#staged = '[++\($count\)](green)'
#renamed = "ðŸ‘…"
#deleted = "ðŸ—‘"

[package]
disabled = false
symbol = "ï£– "

# Others
[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ž "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "îž˜ "

[container]
disabled = true

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[golang]
symbol = "î˜§ "

[haskell]
symbol = "î· "

[hg_branch]
symbol = "ï˜ "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[lua]
symbol = "î˜  "

[memory_usage]
symbol = "ï¡š "

[meson]
symbol = "ï¨¶ "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ïŒ“ "

[nodejs]
symbol = "îœ˜ "

[python]
symbol = "îˆµ "

[rlang]
symbol = "ï³’ "

[ruby]
disabled = true
symbol = "îž‘ "

[rust]
symbol = "îž¨ "

[scala]
symbol = "îœ· "

[spack]
symbol = "ðŸ…¢ "
